### ISSUE TITLE
Add message type to response

### ISSUE THREAD

**Issue by vileyne** [lightna-project/lightna#10]
ATM when we make a request e.g. to add a product to a cart there is a response with messageHtml. It would also be convenient to have a type of the message, based on it some action could be performed so not only the message is shown

<img width="500" alt="Знімок екрана 2024-08-27 о 20 52 47" src="https://github.com/user-attachments/assets/b6a3dd70-cc9c-4bd4-9941-00d8482490b2">

**Comment by vesan-83** [comment]
as there several messages possible, maybe just pass a flag, for example, hasSuccessMessage or so

**Comment by vileyne** [comment]
since it came up as a request from adding to the cart and handling different scenarios, maybe also an idea to modify response for /checkout/cart/add

**Comment by vesan-83** [comment]
I meant flag hasSuccessMessage in response for /checkout/cart/add. Do you mean the same?

**Comment by vesan-83** [comment]
pushed to minicart branch
