### ISSUE TITLE
Build Failed. Configurations Required.

### ISSUE THREAD

**Issue by websnap** [lightna-project/lightna#101]
Run:
composer lightna:build

AR: 
> ./cli compile
clean compiled................ ok
make objects map.............. ok
make config................... ok
make objects schema...........
PHP Fatal error:  Uncaught Exception: Config value storage/opcache/dir required for Lightna\Engine\App\Storage\Opcache in /.../lightna/code/lightna/lightna-engine/App/Compiler/ObjectSchema.php:119
Stack trace:
#0 /.../lightna/code/lightna/lightna-engine/App/Compiler/ObjectSchema.php(82): Lightna\Engine\App\Compiler\ObjectSchema->parseAppConfigPath()
#1 /.../lightna/code/lightna/lightna-engine/App/Compiler/ObjectSchema.php(63): Lightna\Engine\App\Compiler\ObjectSchema->parseClassProperties()
#2 /.../lightna/code/lightna/lightna-engine/App/Compiler/ObjectSchema.php(31): Lightna\Engine\App\Compiler\ObjectSchema->makeObjects()
#3 /.../lightna/code/lightna/lightna-engine/App/Console/Compile.php(105): Lightna\Engine\App\Compiler\ObjectSchema->make()
#4 /.../lightna/code/lightna/lightna-engine/App/Console/Compile.php(97): Lightna\Engine\App\Console\Compile->runItem()
#5 /.../lightna/code/lightna/lightna-engine/App/Console/Compile.php(50): Lightna\Engine\App\Console\Compile->runSequence()
#6 /.../lightna/code/lightna/lightna-engine/cli(23): Lightna\Engine\App\Console\Compile->run()
#7 /.../lightna/entry/magento-os/cli(8): require('...')
#8 {main}
  thrown in /.../lightna/code/lightna/lightna-engine/App/Compiler/ObjectSchema.php on line 119

**Comment by vesan-83** [comment]
this setting moved from  config to env.php
