### ISSUE TITLE
Build Failed. Update Triggers.

### ISSUE THREAD

**Issue by websnap** [lightna-project/lightna#102]
Preconditions:
Magento Inventory modules have been disabled in app/etc/config.php

Run:
composer lightna:build

AR:
PHP Fatal error:  Uncaught ErrorException: Undefined array key "inventory_source_item" in /.../lightna/code/lightna/lightna-engine/App/Update/Schema/Index/Triggers.php:142
Stack trace:
#0 /.../lightna/code/lightna/lightna-engine/App/Update/Schema/Index/Triggers.php(142): Lightna\Engine\App\Bootstrap::Lightna\Engine\App\{closure}()
#1 /.../lightna/code/lightna/lightna-engine/App/Update/Schema/Index/Triggers.php(117): Lightna\Engine\App\Update\Schema\Index\Triggers->getTriggerStatementBody()
#2 /.../lightna/code/lightna/lightna-engine/App/Update/Schema/Index/Triggers.php(83): Lightna\Engine\App\Update\Schema\Index\Triggers->updateTrigger()
#3 /.../lightna/code/lightna/lightna-engine/App/Update/Schema/Index/Triggers.php(75): Lightna\Engine\App\Update\Schema\Index\Triggers->updateTriggers()
#4 /.../lightna/code/lightna/lightna-engine/App/Console/Update.php(15): Lightna\Engine\App\Update\Schema\Index\Triggers->update()
#5 /.../lightna/code/lightna/lightna-engine/App/Cli.php(18): Lightna\Engine\App\Console\Update->run()
#6 /.../lightna/code/lightna/lightna-engine/cli(29): Lightna\Engine\App\Cli->run()
#7 /.../lightna/entry/magento-os/cli(8): require('...')
#8 {main}
  thrown in /.../lightna/code/lightna/lightna-engine/App/Update/Schema/Index/Triggers.php on line 142

**Comment by vesan-83** [comment]
@websnap fixed
