### ISSUE TITLE
Build Failed. Inventory

### ISSUE THREAD

**Issue by websnap** [lightna-project/lightna#104]
Preconditions:
Disabled Magento Inventory modules in app/etc/config.php.

Run:
composer lightna:build

AR:
`PHP Fatal error:  Uncaught Exception: Statement could not be executed (42S02 - 1146 - Table 'lightna_magento_os_2024_11_14_extra_large.inventory_source' doesn't exist).
SQL was: SELECT `s`.`name` AS `name`, `l`.`source_code` AS `source_code`, `l`.`stock_id` AS `stock_id`, `c`.`code` AS `website_code`, `w`.`website_id` AS `website_id` FROM `inventory_source` AS `s` INNER JOIN `inventory_source_stock_link` AS `l` ON `l`.`source_code` = `s`.`source_code` INNER JOIN `inventory_stock_sales_channel` AS `c` ON `c`.`stock_id` = `l`.`stock_id` INNER JOIN `store_website` AS `w` ON `w`.`code` = `c`.`code` WHERE s.enabled = 1 in /.../lightna/code/lightna/lightna-engine/App/DatabaseA.php:104
Stack trace:
#0 /.../lightna/code/lightna/lightna-engine/App/DatabaseA.php(119): Lightna\Engine\App\DatabaseA->sql()
#1 /.../lightna/code/lightna/magento-os-backend/App/Query/Inventory.php(24): Lightna\Engine\App\DatabaseA->fetch()
#2 /.../lightna/code/lightna/lightna-engine/App/ObjectA.php(66): Lightna\Magento\App\Query\Inventory->defineWebsiteSources()
#3 /.../lightna/code/lightna/lightna-engine/App/ObjectA.php(51): Lightna\Engine\App\ObjectA->defineProperty()
#4 /.../lightna/code/lightna/magento-os-backend/App/Query/Inventory.php(39): Lightna\Engine\App\ObjectA->__get()
#5 /.../lightna/code/lightna/magento-os-backend/App/Query/Inventory.php(68): Lightna\Magento\App\Query\Inventory->getWebsiteSources()
#6 /.../lightna/code/lightna/magento-os-backend/Index/Product/Batch.php(180): Lightna\Magento\App\Query\Inventory->getBatch()
#7 /.../lightna/code/lightna/magento-os-backend/Index/Product/Batch.php(75): Lightna\Magento\Index\Product\Batch->loadInventory()
#8 /.../lightna/code/lightna/magento-os-backend/Index/Product/Batch.php(47): Lightna\Magento\Index\Product\Batch->loadData()
#9 /.../lightna/code/lightna/magento-os-backend/Index/Product.php(28): Lightna\Magento\Index\Product\Batch->getData()
#10 /.../lightna/code/lightna/lightna-engine/App/Index/IndexAbstract.php(47): Lightna\Magento\Index\Product->getDataBatch()
#11 /.../lightna/code/lightna/lightna-engine/App/Index/IndexAbstract.php(19): Lightna\Engine\App\Index\IndexAbstract->loadDataBatch()
#12 /.../lightna/code/lightna/lightna-engine/App/Indexer.php(58): Lightna\Engine\App\Index\IndexAbstract->refresh()
#13 /.../lightna/code/lightna/lightna-engine/App/Indexer.php(35): Lightna\Engine\App\Indexer->refreshAll()
#14 /.../lightna/code/lightna/lightna-engine/App/Console/Deploy/Data.php(57): Lightna\Engine\App\Indexer->reindex()
#15 /.../lightna/code/lightna/lightna-engine/App/Console/Deploy/Data.php(21): Lightna\Engine\App\Console\Deploy\Data->deploy()
#16 /.../lightna/code/lightna/lightna-engine/App/Cli.php(18): Lightna\Engine\App\Console\Deploy\Data->run()
#17 /.../lightna/code/lightna/lightna-engine/cli(29): Lightna\Engine\App\Cli->run()
#18 /.../lightna/entry/magento-os/cli(8): require('...')
#19 {main}
  thrown in /.../lightna/code/lightna/lightna-engine/App/DatabaseA.php on line 104`

**Comment by vesan-83** [comment]
fixed
