### ISSUE TITLE
Largest contentful paint element 3,110 ms

### ISSUE THREAD

**Issue by vesan-83** [lightna-project/lightna#75]
![image](https://github.com/user-attachments/assets/4c4146d9-3633-424d-8c1b-753a3474428f)
Can we improve that?

**Comment by vileyne** [comment]
@vesan-83 can we compress the image?

**Comment by vesan-83** [comment]
yes, it's magento configuration.
is it the only issue?

**Comment by vileyne** [comment]
I'd start with that
